name: package-on-tag

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 3.27.9

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build (Linux)
        if: runner.os == 'Linux'
        run: cmake --build build -j

      - name: Build (Windows)
        if: runner.os == 'Windows'
        run: cmake --build build --config Release

      - name: Package with CPack (Linux)
        if: runner.os == 'Linux'
        run: |
          cd build
          cpack -G TGZ
          cpack -G DEB

      - name: Package with CPack (Windows)
        if: runner.os == 'Windows'
        run: |
          cd build
          cpack -G ZIP

      - name: Upload assets to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/*.tar.gz
            build/*.deb
            build/*.zip